### PR TITLE
Add scala version 2.12.13

### PR DESCRIPTION
**Pull request by MihaiBogdanEugen**
Please add a new tag after merging it so I can send a PR for a new homebrew formula.

### CODE REVIEW

**Comment by MihaiBogdanEugen** [comment]
@mazgi take a look at this when you can :)

**Comment by MihaiBogdanEugen** [comment]
@mazgi can you please add a new tag? Or provide me permissions to push tags and I can do it next time.

**Comment by mazgi** [comment]
@MihaiBogdanEugen Thank you for the comment ✨ 
I've just invited you.

**Comment by MihaiBogdanEugen** [comment]
Thank you, I will not let you down!

**Comment by MihaiBogdanEugen** [comment]
@mazgi you've just invited me to sbtenv, which is fine, I plan to keep that one up to date as well. Can I get you invite me to scalaenv as well (the current one)? The tag I want to add is for scalaenv right now.

**Comment by mazgi** [comment]
@MihaiBogdanEugen oops... I've just invited you scalaenv 🙏🏻

**Comment by mazgi** [comment]
@MihaiBogdanEugen Thank you for your comment https://github.com/scalaenv/scalaenv/pull/101#issuecomment-765487587 again ❤️ 
Please mention to @3tty0n before you tag.
Because he is the most active maintainer, I'm respecting him.

**Comment by 3tty0n** [comment]
@MihaiBogdanEugen Thank you for your continuous commitments. Recently, I could not actively commit to this project since I'm pursuing my doctoral course, so I welcome your spontaneous development.  It's not mandatory to mention me when you add a new version tag. If you have any questions, please feel free to ask us.

**Comment by MihaiBogdanEugen** [comment]
@3tty0n not a problem, I know how hard getting a PHd is, my wife has one. Good luck with your endeavours. I'll try to keep both scalaenv and sbtenv up to date with the latest releases. Thank you all for your work so far.

**Pull request merged**
